"""
Fleet Cost & Maintenance Optimizer
----------------------------------

Author:
Andela Stojanovic

Description:
Decision Support System for fleet maintenance planning.

The application evaluates vehicle maintenance risk, optimizes a limited
maintenance budget and generates Key Performance Indicators (KPIs)
to support business decisions.

Designed as a portfolio project for Business Analysis,
Operations Management and Project Management roles.
"""

from dataclasses import dataclass
import pandas as pd

# ==========================================================
# DATA MODEL
# ==========================================================

@dataclass
class FleetKPIs:
    """Stores business KPIs generated by the optimization."""

    fleet_size: int
    high_risk_vehicles: int
    selected_vehicles: int

    available_budget: float
    allocated_budget: float
    remaining_budget: float

    budget_utilization: float

    average_risk_score: float

    net_savings: float

    roi: float

# ==========================================================
# BUSINESS LOGIC
# ==========================================================

class FleetOptimizer:
    """
    Fleet maintenance optimization engine.

    Responsibilities:
    - Load fleet data
    - Calculate maintenance risk
    - Prioritize maintenance
    - Allocate budget
    - Generate KPIs
    - Produce management reports
    """

    def __init__(self, maintenance_budget: float):

        self.available_budget = maintenance_budget

        self.fleet_data = None

        self.allocated_budget = 0.0

        self.net_savings = 0.0

        self.selected_vehicles = []

    # ------------------------------------------------------
    # LOAD DATA
    # ------------------------------------------------------

    def load_fleet_data(self, data: dict) -> pd.DataFrame:
        """
        Loads fleet information into a pandas DataFrame.

        Parameters
        ----------
        data : dict
            Dictionary containing fleet information.

        Returns
        -------
        pd.DataFrame
        """

        self.fleet_data = pd.DataFrame(data)

        return self.fleet_data

    # ------------------------------------------------------
    # RISK SCORE
    # ------------------------------------------------------

    def calculate_risk_score(self) -> pd.DataFrame:
        """
        Calculates maintenance risk for every vehicle.

        Risk Formula

        60% Mileage
        40% Vehicle Age
        """

        if self.fleet_data is None:
            raise ValueError("Fleet data not loaded.")

        self.fleet_data["Risk_Score"] = (
            (self.fleet_data["Mileage"] / 150000) * 0.6
            +
            (self.fleet_data["Age_Years"] / 10) * 0.4
        ).round(2)

        self.fleet_data["Urgent_Action"] = (
            self.fleet_data["Risk_Score"] >= 0.75
        )

        return self.fleet_data
        
    # ------------------------------------------------------
    # RISK CLASSIFICATION
    # ------------------------------------------------------

    @staticmethod
    def classify_risk(score: float) -> str:
        """
        Classifies vehicle maintenance risk.

        Risk Levels
        -----------
        LOW       : < 0.40
        MEDIUM    : 0.40 - 0.59
        HIGH      : 0.60 - 0.74
        CRITICAL  : >= 0.75
        """

        if score < 0.40:
            return "LOW"

        if score < 0.60:
            return "MEDIUM"

        if score < 0.75:
            return "HIGH"

        return "CRITICAL"

    # ------------------------------------------------------
    # IDENTIFY HIGH-RISK VEHICLES
    # ------------------------------------------------------

    def identify_high_risk_assets(self) -> pd.DataFrame:
        """
        Adds a business-friendly risk category
        to every vehicle.
        """

        if "Risk_Score" not in self.fleet_data.columns:
            self.calculate_risk_score()

        self.fleet_data["Risk_Level"] = (
            self.fleet_data["Risk_Score"]
            .apply(self.classify_risk)
        )

        return self.fleet_data

    # ------------------------------------------------------
    # SORT VEHICLES
    # ------------------------------------------------------

    def sort_by_priority(self) -> pd.DataFrame:
        """
        Sorts vehicles by descending risk score.
        """

        if "Risk_Level" not in self.fleet_data.columns:
            self.identify_high_risk_assets()

        self.fleet_data = self.fleet_data.sort_values(
            by="Risk_Score",
            ascending=False
        ).reset_index(drop=True)

        return self.fleet_data

    # ------------------------------------------------------
    # BUDGET OPTIMIZATION
    # ------------------------------------------------------

    def optimize_budget(self):
        """
        Allocates the available maintenance budget
        to the highest-risk vehicles.

        Priority is given to:

        1. Highest Risk Score
        2. Vehicles requiring urgent maintenance
        """

        self.sort_by_priority()

        self.allocated_budget = 0.0
        self.net_savings = 0.0
        self.selected_vehicles = []

        allocation = []

        for _, vehicle in self.fleet_data.iterrows():

            maintenance_cost = vehicle["Est_Maintenance_Cost"]

            allocate = False

            if (
                vehicle["Urgent_Action"]
                and
                self.allocated_budget + maintenance_cost
                <= self.available_budget
            ):

                allocate = True

                self.allocated_budget += maintenance_cost

                self.net_savings += maintenance_cost * 3

                self.selected_vehicles.append(vehicle["Vehicle_ID"])

            allocation.append(allocate)

        self.fleet_data["Budget_Allocated"] = allocation

        return self.fleet_data

    # ------------------------------------------------------
    # KPI CALCULATION
    # ------------------------------------------------------

    def calculate_kpis(self) -> FleetKPIs:
        """
        Calculates business KPIs after budget optimization.
        """

        fleet_size = len(self.fleet_data)

        high_risk = len(
            self.fleet_data[
                self.fleet_data["Urgent_Action"] == True
            ]
        )

        selected = len(self.selected_vehicles)

        remaining_budget = (
            self.available_budget - self.allocated_budget
        )

        budget_utilization = (
            self.allocated_budget
            / self.available_budget
            * 100
        )

        average_risk = (
            self.fleet_data["Risk_Score"]
            .mean()
            .round(2)
        )

        if self.allocated_budget > 0:
            roi = (
                self.net_savings
                / self.allocated_budget
            ) * 100
        else:
            roi = 0

        return FleetKPIs(
            fleet_size=fleet_size,
            high_risk_vehicles=high_risk,
            selected_vehicles=selected,
            available_budget=self.available_budget,
            allocated_budget=self.allocated_budget,
            remaining_budget=remaining_budget,
            budget_utilization=round(budget_utilization, 1),
            average_risk_score=average_risk,
            net_savings=self.net_savings,
            roi=round(roi, 1),
        )

    # ------------------------------------------------------
    # MANAGEMENT RECOMMENDATIONS
    # ------------------------------------------------------

    def generate_recommendations(self) -> list[str]:
        """
        Generates management recommendations
        based on optimization results.
        """

        recommendations = []

        if self.allocated_budget == 0:

            recommendations.append(
                "No maintenance budget has been allocated."
            )

            return recommendations

        utilization = (
            self.allocated_budget
            / self.available_budget
        )

        if utilization >= 0.90:

            recommendations.append(
                "Maintenance budget is being efficiently utilized."
            )

        elif utilization >= 0.70:

            recommendations.append(
                "Budget utilization is satisfactory."
            )

        else:

            recommendations.append(
                "Budget utilization could be improved."
            )

        remaining_critical = len(
            self.fleet_data[
                (self.fleet_data["Risk_Level"] == "CRITICAL")
                &
                (self.fleet_data["Budget_Allocated"] == False)
            ]
        )

        if remaining_critical > 0:

            recommendations.append(
                f"{remaining_critical} critical vehicles remain without maintenance."
            )

            recommendations.append(
                "Consider increasing the maintenance budget."
            )

        else:

            recommendations.append(
                "All critical vehicles have been successfully covered."
            )

        if self.net_savings > self.available_budget:

            recommendations.append(
                "Preventive maintenance generated significant financial benefits."
            )

        return recommendations

    # ------------------------------------------------------
    # EXECUTIVE REPORT
    # ------------------------------------------------------

    def print_executive_report(self):
        """
        Prints a management report with KPIs.
        """

        kpis = self.calculate_kpis()

        print("\n")
        print("=" * 60)
        print("FLEET OPTIMIZATION EXECUTIVE REPORT")
        print("=" * 60)

        print(f"Fleet Size.................. {kpis.fleet_size}")
        print(f"High Risk Vehicles.......... {kpis.high_risk_vehicles}")
        print(f"Vehicles Selected........... {kpis.selected_vehicles}")

        print()

        print(f"Available Budget............ € {kpis.available_budget:.0f}")
        print(f"Allocated Budget............ € {kpis.allocated_budget:.0f}")
        print(f"Remaining Budget............ € {kpis.remaining_budget:.0f}")

        print()

        print(f"Budget Utilization.......... {kpis.budget_utilization}%")
        print(f"Average Risk Score.......... {kpis.average_risk_score}")
        print(f"Estimated ROI............... {kpis.roi}%")
        print(f"Net Savings................. € {kpis.net_savings:.0f}")

        print("=" * 60)

        print("\nVEHICLE SUMMARY\n")

        print(
            self.fleet_data[
                [
                    "Vehicle_ID",
                    "Mileage",
                    "Age_Years",
                    "Risk_Score",
                    "Risk_Level",
                    "Urgent_Action",
                    "Budget_Allocated",
                ]
            ]
        )

        print("\nMANAGEMENT RECOMMENDATIONS\n")

        for recommendation in self.generate_recommendations():

            print(f"✔ {recommendation}")

        print("\n" + "=" * 60)

# ==========================================================
# EXECUTION EXAMPLE
# ==========================================================

def main():
    """
    Demonstration of the Fleet Cost & Maintenance Optimizer.
    """

    # Simulated fleet dataset
    fleet_data = {

        "Vehicle_ID": [
            "V-01",
            "V-02",
            "V-03",
            "V-04",
            "V-05",
            "V-06",
            "V-07",
        ],

        "Mileage": [
            140000,
            45000,
            160000,
            30000,
            125000,
            182000,
            98000,
        ],

        "Age_Years": [
            8,
            2,
            9,
            1,
            7,
            10,
            5,
        ],

        "Est_Maintenance_Cost": [
            1200,
            400,
            1500,
            300,
            1100,
            1700,
            850,
        ],
    }

    # Available annual maintenance budget
    annual_budget = 4000.0

    optimizer = FleetOptimizer(
        maintenance_budget=annual_budget
    )

    optimizer.load_fleet_data(fleet_data)

    optimizer.calculate_risk_score()

    optimizer.identify_high_risk_assets()

    optimizer.optimize_budget()

    optimizer.print_executive_report()


if __name__ == "__main__":
    main()
